# Generated by Django 5.0.7 on 2024-07-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_posts", "0003_tag_post_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="tag",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="icons/"),
        ),
    ]
